import './globals.css'
// import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from '@vercel/analytics/react'
import Head from 'next/head'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${GeistMono.className} `} >
      <Head>
        <title>Seinfeld Calendar</title>
      </Head>
      <body>{children}</body>
      <SpeedInsights />
      <Analytics />
    </ html>
  )
}
